spring.application.name=meter-service
server.port = 8085

spring.data.mongodb.uri=mongodb://localhost:27017/utility_meter_db
spring.data.mongodb.auto-index-creation=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/