spring.application.name=meter-service
server.port=8085
server.error.include-message=always

spring.data.mongodb.uri=mongodb://localhost:27017/utility_meter_db
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/