spring.application.name=meter-service
server.port=8085
server.error.include-message=always

spring.data.mongodb.uri=mongodb://localhost:27017/utility_meter_db

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

eureka.instance.lease-renewal-interval-in-seconds=15
eureka.instance.lease-expiration-duration-in-seconds=45
eureka.client.registry-fetch-interval-seconds=15

#spring.config.import=optional:configserver:http://localhost:8888

spring.cloud.config.fail-fast=false
spring.cloud.config.retry.max-attempts=3
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=2000

spring.config.location=classpath:/application.properties
spring.profiles.active=default
