spring.application.name=billing-service
server.port=8086

spring.data.mongodb.uri=mongodb://localhost:27017/utility_billing_db
spring.data.mongodb.auto-index-creation=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000
server.error.include-message=always
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.cloud.config.enabled=false
spring.kafka.consumer.properties.spring.json.use.type.headers=false