spring.application.name=billing-service
server.port = 8086

spring.data.mongodb.uri=mongodb://localhost:27017/utility_billing_db
spring.data.mongodb.auto-index-creation = true

eureka.client.service-url.defaultZone = http://localhost:8761/eureka/